#!/bin/sh
set -euo pipefail

tmp=$(mktemp -dt shellgrasp.XXXXXX)
for task in tasks/*; do
	printf "\x1b[2J\x1b[H" # clear screen, move to origin at (1;1)
	cat "$task"/task
	echo

	rm -rf "$tmp"/data
	unset SHELLGRASP_CD
	if [ -d "$task"/data-train ]; then
		cp -a "$task"/data-train "$tmp"/data
		export SHELLGRASP_CD="$tmp"/data
	fi

	rm -f "$tmp"/lastcmd
	ENV=.shrc /bin/sh
	res=0

	rm -rf "$tmp"/data
	unset SHELLGRASP_LASTCMD
	if [ -d "$task"/data-test ]; then
		SHELLGRASP_LASTCMD=$(cat "$tmp"/lastcmd)
		export SHELLGRASP_LASTCMD
		cp -a "$task"/data-test "$tmp"/data
		ENV=.shrc /bin/sh
		cmp -s "$tmp"/result "$task"/result || res=1
	fi

	if [ "$res" -gt 0 ]; then
		echo "ОШИБКА"
		echo "ПРАВИЛЬНЫЙ ОТВЕТ:"
		cat "$task"/solution
	else
		echo "ПРАВИЛЬНО"
	fi
	read -p "Нажмите ENTER для продолжения" dummy
done
