#!/bin/sh
set -eu

tmp=$(mktemp -dt shellgrasp.XXXXXX)
for task in tasks/*; do
	printf "\x1b[2J" # clear screen
	printf "\x1b[H" # move cursor to upper left
	cat "$task"/task
	echo

	rm -rf "$tmp"/*
	if [ -d "$task"/workdir ]; then
		cp -a "$task"/workdir "$tmp"
	else
		mkdir "$tmp"/workdir
	fi

	(cd "$tmp"/workdir; HISTFILE="$tmp"/history PS1='$ ' exec /bin/sh) || :

	# Read last command from shell history - this is user's solution.
	# Note, history file may be absent if there were no commands.
	# In this case just ignore open error, solution is empty string.
	# Remove leading and trailing spaces from solution.
	lastcmd=$(tail -1 "$tmp"/history 2>/dev/null | sed 's/^ *//; s/ *$//')
	if echo "$lastcmd" | grep -qExf "$task"/solution.regex; then
		echo "ПРАВИЛЬНО"
	else
		echo "ОШИБКА! ПРАВИЛЬНЫЙ ОТВЕТ:"
		cat "$task"/solution
	fi
	echo "Нажмите ENTER для продолжения"
	read
done
