#!/bin/sh

PS1='$ '

get_lastcmd() {
	local lastcmd

	IFS=" " read num lastcmd <<-EOF
	$(history | tail -1)
	EOF
	# if exit was used to quit shell, get penultimate command
	if [ "$lastcmd" = "exit" ]; then
		IFS=" " read num lastcmd <<-EOF
		$(history | tail -2 | head -1)
		EOF
	fi
	echo "$lastcmd" >../lastcmd
}
trap "get_lastcmd" EXIT
